apt_debian:
  - ansible
  - ansible-lint
  - build-essential
  - curl
  - dialog
  - dnsutils
  - gawk
  - git
  - html2text
  - htop
  - imagemagick
  - less
  - links
  - nmap
  - procps
  - pylint
  - python-is-python3
  - python3-autopep8
  - python3-pip
  - ruby
  - tidy
  - tmux
  - tmux-plugin-manager
  - tree
  - vim-nox
  - yamllint
  - zsh

linuxbrew_linux:
  - bat
  - bat-extras
  - fd
  - fzf
  - git
  - git-delta
  - git-extras
  - go
  - jq
  - k9s
  - lf
  - neovim
  - node
  - npm
  - ripgrep
  - scc
  - shellcheck
  - the_silver_searcher
  - tidy-html5
  - tree
  - tree-sitter
  - zsh
  - zsh-autosuggestions

linuxbrew_linux_source:
  - urlview


go_common:
  - golang.org/x/tools/...@latest
  - github.com/klauspost/asmfmt/cmd/asmfmt@latest
  - github.com/go-delve/delve/cmd/dlv@latest
  - github.com/kisielk/errcheck@latest
  - github.com/davidrjenni/reftools/cmd/fillstruct@master
  - github.com/rogpeppe/godef@latest
  - golang.org/x/tools/cmd/goimports@master
  - golang.org/x/lint/golint@master
  - github.com/mgechev/revive@latest
  - golang.org/x/tools/gopls@latest
  - github.com/golangci/golangci-lint/cmd/golangci-lint@latest
  - honnef.co/go/tools/cmd/staticcheck@latest
  - github.com/fatih/gomodifytags@latest
  - golang.org/x/tools/cmd/gorename@master
  - github.com/jstemmer/gotags@master
  - golang.org/x/tools/cmd/guru@master
  - github.com/josharian/impl@master
  - honnef.co/go/tools/cmd/keyify@master
  - github.com/fatih/motion@latest
  - github.com/koron/iferr@master
