- name: Build image
  hosts: localhost
  gather_facts: false
  vars:
    docker_base: debian-bullseye-base
    docker_image: debian:bullseye
  roles:
    - docker_build

- name: Bootstrap Debian
  hosts: debian-bullseye-base
  gather_facts: false
  vars:
    docker_base: debian-bullseye-base
    user_name: oddee
    user_group: users
    user_groups: sudo
    user_shell: /bin/zsh
    user_password: $6$0i08C4gqOhx6NMqv$cXIKw5KpHdBgN5k79Vf9xUcDfxbJBTX3XvH41vT3/UWjFaAhxmnv35ouZLxm/9N6RowMjvsHQYbXhSj5tvH8g0
  roles:
    - docker_debian

- name: Setup Debian
  hosts: debian-bullseye-base
  vars:
    hostname: debian-wsl
  roles:
    - common
    - linux_debian
    - linux_brew

- name: Snapshot container
  hosts: localhost
  gather_facts: false
  vars:
    docker_base: debian-bullseye-base
    docker_build: debian-bullseye-base
  roles:
    - docker_snapshot

