- name: Upgrade all Pacman packages
  community.general.pacman:
    update_cache: true
    upgrade: true
  become: true

- name: Install pacman packages from list 'archlinux_pacman_pkgs'
  community.general.pacman:
    pkg: "{{ archlinux_pacman_pkgs }}"
    state: latest
  become: true
  when: archlinux_pacman_pkgs is defined

- name: Install Ansible AUR module
  community.general.ansible_galaxy_install:
    name: kewlfft.aur
    type: collection
  become: true

- name: Install yay from AUR
  kewlfft.aur.aur:
    name: yay
    use: makepkg
    state: latest
  become: true
  become_user: "{{ ansible_user_id }}"

- name: Install AUR packages from 'archlinux_aur_pkgs'
  kewlfft.aur.aur:
    use: yay
    name: "{{ archlinux_aur_pkgs }}"
    state: latest
  become: true
  become_user: "{{ ansible_user_id }}"

