- name: Set password for user root
  ansible.builtin.user:
    name: root
    password: "{{ user_password }}"

- name: Give sudo access to group wheel
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/00-wheel
    line: '%wheel ALL=(ALL:ALL) NOPASSWD: ALL'
    create: true
    validate: 'visudo -cf %s'

- name: Add user {{ user_name }} with primary group {{ user_group }}
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_group }}"
    groups: "{{ user_groups }}"
    shell: "{{ user_shell }}"
    password: "{{ user_password }}"

- name: Re-add Docker container {{ docker_base }} to Ansible hosts inventory
  ansible.builtin.add_host:
    name: "{{ docker_base }}"
    ansible_connection: docker
    ansible_ssh_user: "{{ user_name }}"


