- name: Upgrade all APT packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoclean: true
    autoremove: true
  become: true

- name: Install APT packages from list 'apt_debian'
  ansible.builtin.apt:
    pkg: "{{ apt_debian }}"
    state: latest
    autoclean: true
    autoremove: true
    install_recommends: no
  become: true
  when: apt_debian is defined
