- name: Snapshot Docker container {{ docker_base }} as {{ docker_build }}
  ansible.builtin.command: docker commit {{ docker_base }} {{ docker_build }}
  when: true

- name: Stop Docker container {{ docker_base }}
  community.docker.docker_container:
    name: "{{ docker_base }}"
    state: absent
    force_kill: true

